export const OPEN_INGRIDIENT = 'OPEN_INGRIDIENT';
export const CLOSE_INGRIDIENT = 'CLOSE_INGRIDIENT';
export const ADD_INGRIDIENT_TO_CONSTRUCTOR = 'ADD_INGRIDIENT_TO_CONSTRUCTOR';
export const DEL_INGRIDIENT_FROM_CONSTRUCTOR = 'DEL_INGRIDIENT_FROM_CONSTRUCTOR';
export const DECRIMENT_INGRIDIENT_COUNT = 'DECRIMENT_INGRIDIENT_COUNT';
export const SWAP_INGRIDIENT_IN_CONSTRUCTOR = 'SWAP_INGRIDIENT_IN_CONSTRUCTOR';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_ERROR = 'ORDER_ERROR';
export const ORDER_CLEAR = 'ORDER_CLEAR';
export const INGRIDIENTS_LIST_REQUEST = 'INGRIDIENTS_LIST_REQUEST';
export const INGRIDIENTS_LIST_SUCCESS = 'INGRIDIENTS_LIST_SUCCESS';
export const INGRIDIENTS_LIST_ERROR = 'INGRIDIENTS_LIST_ERROR';
export const Tabs = {
  BUN: 'bun',
  SAUCE:'sauce',
  MAIN:'main',
};
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';
export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR';
export const PASSWORD_FORGOT_REQUEST = 'PASSWORD_FORGOT_REQUEST';
export const PASSWORD_FORGOT_SUCCESS = 'PASSWORD_FORGOT_SUCCESS';
export const PASSWORD_FORGOT_ERROR = 'PASSWORD_FORGOT_ERROR';
