export const ADD_INGRIDIENTS_LIST = 'ADD_INGRIDIENTS_LIST';
export const OPEN_INGRIDIENT = 'OPEN_INGRIDIENT';
export const CLOSE_INGRIDIENT = 'CLOSE_INGRIDIENT';
export const ADD_INGRIDIENT_TO_CONSTRUCTOR = 'ADD_INGRIDIENT_TO_CONSTRUCTOR';
export const DEL_INGRIDIENT_FROM_CONSTRUCTOR = 'DEL_INGRIDIENT_FROM_CONSTRUCTOR';
